### ISSUE TITLE
mavm provides not yet active accounts with unverified payment method

### ISSUE THREAD

**Issue by sbstjn** [superwerker/aws-organizations-vending-machine#16]
Sometimes accounts do not get a verified payment method, therefore the account cannot be used to create resources. AWS sends an email to notify the account about this issue with the topic "Amazon Web Services Account Alert".

When logging in to an unactive account, an error message is displayed:

> We were unable to verify your default payment method. To avoid payment failures, and potential disruption in using AWS services, please contact your bank to determine the reason and visit this page to verify your payment method. You can also choose to add another card.

In the superwerker pipeline, this leads to this error message:

> An error occurred (OptInRequired) when calling the CreateStack operation: The AWS Access Key Id needs a subscription for the service

## Ideas

- Do not "handle" this
- Close the created AWS account

**Comment by s0enke** [comment]
fixed with f27b02103d850ef7836b74f92381465412dc542a
